### ISSUE TITLE
Several errors when deploying Data Product Streaming

### ISSUE THREAD

**Issue by sebclaude** [Azure/data-product-streaming#54] opened 2021-07-30 15:40 UTC
**Describe the bug**

Several deployment errors appears when deploying Data Product Streaming :
- during synapse deployment 
- during cosmos deployment
- during role assignment

**Steps to reproduce**

1. Deploy DMZ and DLZ using global template
2. Deploy Streaming Data Product in ressources group 001 created during step 1

**Screenshots**

![image](https://user-images.githubusercontent.com/9470200/127676909-34cbf096-3037-4e18-b5fc-ce1471b0f4e6.png)

![image](https://user-images.githubusercontent.com/9470200/127676975-8570b0a1-3a9a-445a-b70a-bbc7615278de.png)

**Synapse -> Seems related to Private endpoint deployment**
![image](https://user-images.githubusercontent.com/9470200/127677220-18b2f3c3-1e3d-4ec6-a3bb-152c80808f1a.png)

**Cosmos -> Seems related to Private endpoint deployment**
![image](https://user-images.githubusercontent.com/9470200/127677316-1279bb33-891e-4fab-9939-aca49fbc43cd.png)

**Role Assignment -> Principal Not found**
![image](https://user-images.githubusercontent.com/9470200/127677452-1dc43c30-a544-492c-998f-6168f285f553.png)

**Comment by marvinbuss** [comment] 2021-08-02 17:49
Thanks @sebclaude for submitting this. The private endpoint issues seem to be intermittent. I cannot reproduce them. The role assignment is something I can reproduce and I am currently working on a fix for this.

Let me also reach out to the product team to understand how we can make this more reliable.

**Comment by marvinbuss** [comment] 2021-08-02 19:16
@sebclaude I fixed the role assignment error and merged the PR. If we cannot reproduce the Private endpoint issues in the next few issues, I will close the item for now.

**Comment by marvinbuss** [comment] 2021-08-06 11:25
Update: We are starting to investigate this issue.

**Comment by marvinbuss** [comment] 2021-09-01 21:00
Closing this for now, since the investigation of the support team was not successful and issue is not reproducible. Will reopen, if this occurs again.

**Closed by marvinbuss** 2021-09-01 21:00 UTC
Labels: bug
